### ISSUE TITLE
Maria: separation-of-concerns, 3 weeks

### ISSUE THREAD

**Issue by MMikhailova** [lab-brussels-1/home#368]
## Learning Objectives

<details>
<summary>Priorities: 🥚, 🐣, 🐥, 🐔 (click to learn more)</summary>
<br>

There is a lot to learn in this repository. If you can't master all the material
at once, that's expected! Anything you don't master now will always be waiting
for you to review when you need it. These 4 emoji's will help you prioritize
your study time and to measure your progress:

- 🥚: Understanding this material is required, it covers the base skills you'll
  need to move on. You do not need to finish all of them but should feel
  comfortable that you could with enough time.
- 🐣: You have started all of these exercises and feel you could complete them
  all if you just had more time. It may not be easy for you but with effort you
  can make it through.
- 🐥: You have studied the examples and started some exercises if you had time.
  You should have a big-picture understanding of these concepts/skills, but may
  not be confident completing the exercises.
- 🐔: These concepts or skills are not necessary but are related to this module.
  If you are finished with 🥚, 🐣 and 🐥 you can use the 🐔 exercises to push
  yourself without getting distracted from the module's main objectives.

---

</details>

- [ ] 🥚 **event-driven programming**: identify the concept in a JS program via listeners & handlers
- [ ]🥚 **entry points**: describe what an entry point is, there are 2 kinds in the programs for this module - initialization & interaction. identify them in a program
- 🥚 **function roles**: describe what function roles are and why they're important. they can identify a function's role given checklists for each role covered in this module:
  - [ ] **_listeners_**: functions that attach event listeners to the DOM
  - [ ] 🥚 **_handlers_**: entry point for user interactions
  - [ ] 🥚 **_utils_** _(utilities)_: pure functions to help do things with data
  - [ ] 🐣 **_components_**: render data into DOM elements to display for the user
  - [ ] 🐥 **_custom events_**: create custom events events in your components, passing useful data between components and handlers
- [ ] 🥚 **DOM access**: You read and write values from the DOM in an event handler
- [ ] 🥚 **es5 vs. es6**: You can demonstrate the change in developer-experience pre and post es6 by stepping through in the debugger and explaining differences in scoping \(global vs. script, block vs. local, modules\) between two programs with identical user experience but different implementations.
- [ ] 🥚 **Scope Hierarchy**: You is comfortable navigating different scopes in the browser's debugger to understand an existing application \(script, module, closure, local, block\)
- [ ] 🥚 **Code Splitting**: You can use ES Modules to split your code into multiple files & folders according to function role, data, listeners and initialization. They can use generated dependency diagrams and documentation to understand and navigate this folder structure.
- [ ] 🥚 **Dependency Graphs**: You can use a project's dependency graph to understand how it is organized and to navigate the source code.
- [ ] 🥚 **Development Strategies**: You can write development strategies that have all of the program's state defined at the beginning, and separate each user story into _interface_ and _interaction_ tasks.
- [ ] 🐣 **Naming Functions**: You can come up with clear and helpful names for the functions in your program. A good function name will take into account the function's role and the program's domain, like in the `/naming-variables` exercises from Debugging.
- [ ] 🐣 **DOM manipulation**: You can manipulate the DOM when implementing level-appropriate user interactions
- [ ] 🐣 **Isolating Components**: You can use a `test.html` file to render your components with different inputs
- [ ] 🐣 **Forms**: You can do basic handling of form data via `event.target.form`
- [ ] 🐣 **Handling events**: You can use the `event` argument to process user interactions, including bubbled events using `event.target`
- [ ] 🐣 **Passing Component Unit Tests**: You can write vanilla DOM component functions to pass provided unit tests
- [ ] 🐣 **refactoring**: refactor a single-script tutorial-style web page into multiple files using imports and exports
- [ ] 🐥 **reverse-engineering**: You can incrementally reverse-engineer a level-appropriate user interaction following these steps:
  - _init_
  - Listeners
  - Handlers
  - (possibly): Utils, Components, Custom Events
- [ ] 🐔 **From Spec**: given user stories, You can develop a site from scratch using a template repository.
- [ ] 🐔 **Writing Component Unit Tests**: You can write unit tests to validate your component functions using BDD syntax

**Comment by MMikhailova** [comment]
Week 1

## I Need Help With:

 ```<script type="module" src="./src/init.js"></script>``` 
 What is ```type=''module"``` here?

## What went well?
I took my time to review DOM and only then started exercises so it was nice to get through this again and in more detail.

## What went less well?

Since it took me some time to refresh DOM manipulation, I haven't studied `2-listeners-and-handlers` and `3-stepped` yet... I am going to catch up by Sunday class. Also if the meeting is still possible, it would be great to go through `function roles` one more time as we did on Sunday class.

I also have one small suggestion that would help me personally to be more efficient on coming classes.
I try to study more intensively at the beginning of the week to keep Sunday class learnings fresh. Therefore I am normally done with homework by Thursday and do my preparation for Sunday class. It is more complicated for me to study on Weekend because of domesticity. It would be really helpful for me to know about what we are going to learn on Sunday a bit in advance (on Thursday for example). I know that you normally let us know on Thursday/ Friday , so please keep doing it:)

## Lessons Learned


## Sunday Prep Work
I am studying `2-listeners-and-handlers` and `3-stepped`

**Comment by danielhalasz** [comment]
> What is `type=''module"` here?

Here is a nice explanation about it: https://javascript.info/modules-intro

**Comment by danielhalasz** [comment]
I think we have addressed the others topics yesterday in the call, if not, let me know.

**Comment by MMikhailova** [comment]
> I think we have addressed the others topics yesterday in the call, if not, let me know.

Absolutely! 
Thank you again for your time🙏

**Comment by MMikhailova** [comment]
Week 2

Here is our project [repo](https://github.com/lab-brussels-1/Group6-separation-of-concerns-starter)

## I Need Help With:

I'm still a little confused with merging and rebasing. When I create a branch from other branch than master. How can I merge it with master then?

E.g
master-->maria_code1
maria_code1-->maria_code2
somebody changed master
How to merge maria_code2-->master
?

## What went well?

I think I understood the separation of concerns concept more or less.
At least I was able to solve all exercises in 'separation_of_concerns' that I have tried.

With our project, we completed planning files in two days. I really enjoyed working in a team this time as it was fast and productive.

## What went less well?

Since we split the work on the project by HTML and JS parts instead of user stories, it took me a lot of time to make my JS code fits HTML code of my teammate. Finally, we reviewed the result together and discussed separation topic.
At the moment, I have written the code for following user stories : 
As a user I want to
`chose items from a catalogue`
`see a list of chosen items in my basket`
`remove chosen items by changing amount by 0`
 `add a new item to my list`

You can see the separation in this [branch](https://github.com/lab-brussels-1/Group6-separation-of-concerns-starter/tree/seconde). P.S I know the name of the branch is not good:)

After I spent huge amount of time by writing my own functions and thinking out separation, all exercises in our repo seem to be easy now:)

I am also happy that I was able to help some mates, because it is even more rewarding to see progress of others:)

## Lessons Learned
Don't try to take any challenges:) Think if it needs to be taken.

## Sunday Prep Work
Still working on our project

**Comment by MMikhailova** [comment]
Week 3

## I Need Help With:

Lint issue in my PR: [lab-brussels-1/Group6-separation-of-concerns-starter/pull/15]

## What went well?

I have rewritten the JavaScript code for our group project with the aim of making it conciser and using objects for storing list. After some time and attempts I have manage to do it. We work well with my teammate, it's motivating.


## What went less well?

The next two classes I will only be able to attend online, I'm a little worried about that.


## Lessons Learned

Separate your code based on user stories. 
The level of cooperation within the team depends on the motivation of its members.

## Sunday Prep Work
I have watched  JS Event Loop.

**Comment by MMikhailova** [comment]
## Me

### What was not clear, where did you get stuck?

At the beginning of the module, the separation of concerns concept was unclear and frightening for me. 

Regardless of this module, I still have some doubts about npm checks and Git Branching.

### What was clear, what did you master?

Throughout the module, I became more and more familiar with separation of concerns concept  by debugging examples, doing exercises and listening coaches. 

Now I am familiar with:

- ` DOM access`
- ` function roles`
- `Code Splitting`
- `Handling events`
- `reverse-engineering`

### Where can you help others moving forwards?

I am always happy to share what I learned but not always feel like I should do it.

 ---

## The Course

### What can there be more of?

Assignments review to understand where you could do better.

### What can there be less of?

Teamwork

### What material were most helpful (from HYF or elsewhere)?

As usual, I think there is plenty of useful information in our repo that we can practice in Study lenses. 
I did not use third party resources in this module.

### Any suggestions for future classes?

Don't be lazy to study all information in the repo, it will save the time of yours, coaches and your teammates.
Be prepared to the classes.
